contact_links:
    - about: 'Have a question about using this software, or about Genixor in general? Post it on the Genixor Stack Exchange.'
      name: Ask a Question
      url: 'https://Genixor.stackexchange.com/questions/ask'
    - about: 'Start or join a discussion on the Genixor Tech Discord.'
      name: Start a Discussion
      url: 'https://Genixor.com/discord'
